repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88']

# Temporarily disabled until type annotations are added
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-setuptools, pytest]
  #       args: [--explicit-package-bases, --namespace-packages]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash
        args:
          - "-c"
          - |
              cd geneweb_python 2>/dev/null || exit 0
              PY_CMD="${PYTHON:-}"
              if [ -z "$PY_CMD" ]; then
                if [ -x .venv/bin/python ]; then
                  PY_CMD=.venv/bin/python
                elif command -v python3 >/dev/null 2>&1; then
                  PY_CMD=python3
                else
                  PY_CMD=python
                fi
              fi
              "$PY_CMD" -m pytest tests/ --tb=short -q --no-cov
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-commit]
